### ISSUE TITLE
Could not process database: pq: column min_time does not exist

### ISSUE THREAD

**Issue by mcook08** [pganalyze/collector#10]
When running `pganalyze-collector --config=/etc/pganalyze-collector.conf --test`
I get this for one of my databases
`Could not process database: pq: column "min_time" does not exist`

I re-created the functions to make sure they were up to date. My postgres instance is on 9.6.1. Any ideas?

**Comment by lfittl** [comment]
Hi @mcook08,

This typically happens when you upgrade the database but didn't upgrade the pg_stat_statements extension. The steps to upgrade the extension are:

* Drop any objects that depend on the extension, in particular the pganalyze.get_stat_statements() helper
* `ALTER EXTENSION pg_stat_statements UPDATE`
* Re-create the objects you dropped, in particular make sure the [monitoring functions](https://github.com/pganalyze/collector#setting-up-a-restricted-monitoring-user) are still setup correctly

Let me know if that works / doesn't work :)

**Comment by mcook08** [comment]
That worked wonderfully! Thanks so much!
