### ISSUE TITLE
SIGSEGV: segmentation violation on 0.38.0

### ISSUE THREAD

**Issue by VVilaplana** [pganalyze/collector#169]
I just installed latest stable (0.38.0) on three VMs (Debian 10.8 with PostgreSQL 13.2) with different cpu/mem sizes and the three of them crashed with a **signal SIGSEGV: segmentation violation error**.  The process restarts and it crashes again every 10 mins.

Please find attached traceback log:

[pganalyze_segv.log](https://github.com/pganalyze/collector/files/6244247/pganalyze_segv.log)

**Comment by lfittl** [comment]
@VVilaplana Thanks for the report!

This looks like a crash in the normalization function. Could you send us a copy of the result of "SELECT * FROM pg_stat_statements" to support@pganalyze.com?

(I would recommend not posting here on GitHub, since Postgres does not always sanitize queries completely, which is why we run this second pass of normalization in the collcetor)

**Comment by lfittl** [comment]
@VVilaplana The fix for this has been released now with the collector 0.38.1 - please let us know in case you're still seeing any issues!
