### ISSUE TITLE
Atlassian OpsGenie Integration Support?

### ISSUE THREAD

**Issue by booleanbetrayal** [pganalyze/collector#250]
We noticed that PGAnalyze has direct PagerDuty and Slack integrations available for critical alerting. As we are evaluating SRE options, we were wondering if [OpsGenie](https://www.atlassian.com/software/opsgenie) might be an integration you would be adopting. Right now it's looking like a compelling option for us, but we're also exploring the use of PGAnalyze alerting and trying to ascertain trade-offs.

Thanks for any insight and keep up the good work!

**Comment by uhoh-itsmaciek** [comment]
Thanks for reaching out. We're definitely interested in adding other alerting integrations (and OpsGenie is near the top of the list), but we're focused on other work right now. When we add support, we'll announce that in our newsletter. If you're interested in beta-testing before it's generally available, please contact support@pganalyze.com and we'll get in touch with you once we have something to share.

I'm going to close this ticket since this functionality is orthogonal to the collector, but please let us know if you have any other feedback.

**Comment by cjestel** [comment]
Any other updates on this? I saw an email a little over a year ago related to this and would be happy to help from a beta testing perspective.

**Comment by lfittl** [comment]
> Any other updates on this? I saw an email a little over a year ago related to this and would be happy to help from a beta testing perspective.

Thanks for the interest! We have heard consistent requests for this, and adding a direct integration with OpsGenie is on the short list for an upcoming product sprint on our end. For context, we have a few items related to alerting that we hope to prioritze in the next 3-6 months, including OpsGenie support. Note that this ETA is rough and may still change.

We'd be happy to reach out for additional feedback / early access testing if applicable.
