### ISSUE TITLE
Running collector inside AWS Lambda

### ISSUE THREAD

**Issue by moltar** [pganalyze/collector#274]
Lambda supports Docker containers.

I am wondering if it is something that was tried already?

If not, is this feasible? I don't see why not. But wondering if you have any opinions before I attempt this.

My observation is that the collector runs every minute, is that right? 

Is there anything that happens during startup/init that is different from what happens after? I.e. some overhead I am missing? Maybe pre-loading stuff or scanning schemas?

Thanks.

**Comment by lfittl** [comment]
@moltar Thanks for your patience on this question!

(FYI, we don't generally monitor issues here, so opening a support ticket is advised, e.g. to point out that you opened an issue 😄)

The collector actually has a very intentional scheduling logic, see https://github.com/pganalyze/collector/blob/main/scheduler/scheduler.go#L86 for some idea of that. Additionally, the collector keeps both in-memory and on-disk state (the latter is only used in practice when running on a VM and restarting the service).

Due to this architecture, running the collector in a short-lived process, such as Lambda doesn't really make sense.

For additional context: The state logic is required to keep the prior stats around, as Postgres has a lot of counter values (that get incremented with new values), and so to have a sense for "what happened in the last 10 minutes" one needs to be able to compare the current value to the prior value. Any attempt at making the collector work in Lambda would require another state keeping mechanism.

Note that you can run the collector in Amazon ECS, which works pretty well.

**Comment by moltar** [comment]
Thanks for the response.

> Note that you can run the collector in Amazon ECS, which works pretty well.

This is what we do now already.

Closing the issue as this answers my question.

Again, thank you!
