### ISSUE TITLE
How to build from source for different GOOS and GOARCH

### ISSUE THREAD

**Issue by jschaf** [pganalyze/collector#279]
I'm not sure how to build pganalyze from source. I'd like to compile the collector binary for linux amd64. Here's what I tried.

```sh
GOOS=linux GOARCH=amd64 make build_dist

fatal: no tag exactly matches '1d88911c8dd7582c60e278192bbf05af2b38ff37'
go build -o pganalyze-collector
package github.com/pganalyze/collector
        imports github.com/pganalyze/collector/config
        imports github.com/pganalyze/collector/util
        imports github.com/pganalyze/pg_query_go/v2
        imports github.com/pganalyze/pg_query_go/v2/parser: build constraints exclude all Go files in /opt/p/pganalyze/vendor/github.com/pganalyze/pg_query_go/v2/parser
make: *** [build_dist] Error 1
```

**Comment by uhoh-itsmaciek** [comment]
That "fatal" error is not actually fatal (see #280), but not sure about cross-compiling or the later error. We'll follow up once we have more info.

**Comment by lfittl** [comment]
@jschaf The actual error here is because the `pg_query_go` package uses CGO, and in my understanding you can't cross-compile in that case: https://github.com/golang/go/issues/29074

We do actually have cross-platform builds in the packaging workflow (see `packages/` folder) but that uses Docker's cross-platform support (which emulates the other platform), rather than using cross-compilation.

In case you don't need cross-compilation, just dropping the GOOS and GOARCH settings should make things work (and as Maciek noted the fatal error is actually a red herring).
