### ISSUE TITLE
Could not collect activity for server

### ISSUE THREAD

**Issue by aviau** [pganalyze/collector#373]
Hello!

I am in the process of upgrading from v0.46.1 to v0.48.0 to benefit from IAM Auth support.

I am now getting the following error:
```
Could not collect activity for server: could not get default grant for activity snapshot: https://api.pganalyze.com/v2/snapshots/grant giving up after 5 attempt(s)
```

I haven't changed much, except:
- Added `db_use_iam_auth=true`
- Added `aws_region=us-east-1`
- Added `api_system_type=amazon_rds` which seems required for IAM Auth now. (should it?)

Any idea what could cause this?

Note also that I get the following message on startup: `Skipping config section db1, detected as duplicate`

This is interesting because I have no duplicates.

My config looks like this:

```
[pganalyze]
api_key=4YOIOZM42RYN7GNM
api_system_type=amazon_rds
aws_region=us-east-1
max_collector_connections=20

[db1]
db_url=postgresql://pganalyze@db1.endpoint.proxy-censored.us-east-1.rds.amazonaws.com/db
db_sslmode=require
db_use_iam_auth=true

[db2]
db_url=postgresql://pganalyze@db2.endpoint.proxy-censored.us-east-1.rds.amazonaws.com/db
db_sslmode=require
db_use_iam_auth=true
```

**Comment by lfittl** [comment]
@aviau 

That seems odd - it should not be necessary to use `api_system_type=amazon_rds` - maybe the issue here is the use of RDS proxy endpoints. Could you use the regular database endpoint (without proxy), and see whether that makes a difference?

The duplicate warning seems to stem from the fact that both db_urls are the same in your config.

**Comment by aviau** [comment]
> The duplicate warning seems to stem from the fact that both db_urls are the same in your config.

They are not. The "censored" part is different.

**Comment by aviau** [comment]
@lfittl 

> Could you use the regular database endpoint (without proxy), and see whether that makes a difference?

I can't, security groups will not allow this.

**Comment by aviau** [comment]
I guess I was happy using self-managed mode with IAM Auth, but it looks like this isnt' supported due to the check that you added.

**Comment by aviau** [comment]
```
				skip := false
				for _, server := range conf.Servers {
					if config.Identifier == server.Identifier {
						skip = true
					}
				}
				if skip {
					logger.PrintError("Skipping config section %s, detected as duplicate", config.SectionName)
				} else {
					conf.Servers = append(conf.Servers, *config)
				}
```

Ah, I didn't specify the identifier in the past so it may be the problem.

**Comment by lfittl** [comment]
> I guess I was happy using self-managed mode with IAM Auth, but it looks like this isnt' supported due to the check that you added.

Ah, interesting - yeah, I think what probably happened is that your server was detected as "self-managed", not as RDS (due to the RDS proxy URL being a different format), and that's why the branch wasn't triggering as expected.

I think what might be best is if you explicitly set `aws_db_instance_id` (or `aws_db_cluster_id`), that should then also translate to the correct `api_system_id`.

**Comment by aviau** [comment]
Its alive!

![image](https://user-images.githubusercontent.com/2706882/215894637-55c89c3b-929b-47e3-b808-8ba6b6b817ed.png)

**Comment by aviau** [comment]
Thanks for helping!

**Comment by lfittl** [comment]
@aviau Nice, happy to see its working! 🚀
